[options]
addons_path = /home/smoawad/odoo/odoo-codebase/odoo-17/addons,
	/home/smoawad/odoo/odoo-codebase/odoo-17/odoo/addons,
	/home/smoawad/odoo/enterprise/enterprise-17.0/enterprise-17.0,
	/home/smoawad/odoo/projects/project-v17/Taskbridge_custom_addons
db_host = localhost
db_port = 5432
db_user = odoo17
db_password = admin
http_port = 8017
admin_passwd = $pbkdf2-sha512$600000$3hsjpDTGmHOuNYbQmjNGCA$mPdKaosaYjBvI83jjzR8Ti/Uqsjo46JVaeIzPdQ2cSXLyOjtoDUr1FRCwAgUr.IbbE.vg4YT6QJXUpOFXZXv5w

